CREATE TABLE products(
   product_id       INTEGER PRIMARY KEY
  ,product_category TEXT
  ,product_name     TEXT
  ,product_desc     TEXT
  ,product_price    NUMERIC(5,2)
  ,product_image    TEXT
);
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (2,'featured','CHICKEN BUCKET LIST','As one of Texas'' premiere beer joints, we''ve got a lot of traditions that have come up over the last 42 years! The back of the shirt has a nice list of things that should be on your Dixie Chicken bucket list. The front will make you want to stand and say the Texas pledge! Be sure to grab your Texas themed Bucket list shirt ASAP.',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/20170224162712_grande.jpg?v=1487975321');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (3,'featured','TRACTOR HAT','Riding the tractor all day never looked so good! This hat comes in Green/Yellow and Brown/Cream.',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_8934_grande.jpg?v=1483127431');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (4,'featured','RATTLESNAKE','One of the most famous aspects of the Dixie Chicken is having a live rattlesnake! Share this piece of history with everyone that sees you with our Rattlesnake T-Shirt. - Gildan, 100% cotton, unisex',22.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_0616_grande.jpg?v=1483119023');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (5,'featured','DIXIE CHICKEN FLAG','Fly the Dixie Chicken high at home or on vacation with your very own Dixie Chicken flag!',40.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/DixieFlag_grande.jpg?v=1484937310');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (6,'featured','CIRCLE LOGO','The best selling Dixie Chicken T-shirt! The full colored, Dixie Chicken circle logo on the back and name on the front left. Much like the Chicken itself, these shirts are timeless. -Gildan, 100% cotton, unisex',22.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_0233_grande.png?v=1484937490');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (8,'men','CHICKEN BUCKET LIST','As one of Texas'' premiere beer joints, we''ve got a lot of traditions that have come up over the last 42 years! The back of the shirt has a nice list of things that should be on your Dixie Chicken bucket list. The front will make you want to stand and say the Texas pledge! Be sure to grab your Texas themed Bucket list shirt ASAP.',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/20170224162712_grande.jpg?v=1487975321');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (9,'men','CIRCLE LOGO','The best selling Dixie Chicken T-shirt! The full colored, Dixie Chicken circle logo on the back and name on the front left. Much like the Chicken itself, these shirts are timeless. -Gildan, 100% cotton, unisex',22.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_0233_grande.png?v=1484937490');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (10,'men','CIRCLE LOGO, LONGSLEEVE','The classic circle logo in a super comfortable long sleeve! This navy blue shirt will keep ya warm on the back porch and around the world. - Comfort Colors, 100% cotton, unisex',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_0254_grande.jpg?v=1483564867');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (12,'men','EXPERIENCE THE TRADITION','The tradition of the Dixie Chicken goes back to 1974. Generations of Aggies have come through our doors for good times with great friends! Wherever you go, let people know they too should go experience the tradition of the Chicken! - Gildan, 65% polyester 35% cotton, unisex',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_0509_copy_grande.jpg?v=1483116764');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (13,'women','DIXIE CHICKEN TANK TOP','For those hot days on the back porch, there''s the Dixie Chicken tank top. Stay cool my friends! - American Apparel, 50% polyester 25% combed cotton 25% rayon',20.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_0513_grande.jpg?v=1483115387');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (14,'women','FISHING SHIRT','Whether your hitting the water or hitting up Northgate, this Dixie Chicken fishing shirt will keep you looking good! It comes in light blue or white. - Columbia, 100% polyester, unisex',65.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_8862_grande.jpg?v=1483123850');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (15,'women','FRONT PORCH','Simple and incredibly soft! This shirt has a retro look with the distressed &#34;DIXIE CHICKEN&#34; across the front. - American Apparel, 50% polyester 25% combed cotton 25% rayon, unisex',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_0230_grande.jpg?v=1483721037');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (16,'women','RATTLESNAKE','One of the most famous aspects of the Dixie Chicken is having a live rattlesnake! Share this piece of history with everyone that sees you with our Rattlesnake T-Shirt. - Gildan, 100% cotton, unisex',22.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_0616_grande.jpg?v=1483119023');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (17,'women','RING DUNK','Show your pride in your Ring Dunk with this shirt! Just write in your time in the open space! - Gildan, 100% cotton, unisex',22.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_0624_grande.jpg?v=1483119390');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (18,'women','SHOTGUN','This basic black t-shirt is perfect for the gun lover and Dixie Chicken lover in your life. - Gildan, 100% cotton, unisex',22.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_0582_grande.jpg?v=1483116738');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (19,'hats','''74 HAT - DISTRESSED','This worn looking hat has become one of our more popular hats. Keep the sun out of your eyes in comfort and style!',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_8899_grande.jpg?v=1483125345');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (20,'hats','''74 HAT - STRUCTURED','This popular logo looks great on this structured hat. Look patriotic in red, white, and blue. - Richardson 112, adjustable',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_8931_grande.jpg?v=1483627698');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (21,'hats','DIXIE CHICKEN VISOR','Hitting the golf course, fishing the lake, or just looking to get a little sun on your hide while keeping the sun out of your eyes, this visor will treat ya well!',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_8985_grande.jpg?v=1483128499');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (22,'hats','DIXIE CHICKEN/CHILIFEST HAT','The Chicken and Chilifest, a match made in a beer lovers heaven! Get your own hat with the two iconic brands together today. - shamrock green, distressed hat.',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/20170320155622_grande.jpg?v=1490043461');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (23,'hats','RUSTIC','This hat has an old school look with simple &#34;Dixie Chicken&#34; as the centerpiece. Perfect for walking to class or sitting out by the lake or pool!',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_8912_grande.jpg?v=1483126178');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (24,'hats','TRACTOR HAT','Riding the tractor all day never looked so good! This hat comes in Green/Yellow and Brown/Cream.',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_8934_grande.jpg?v=1483127431');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (11,'men','CIRCLE LOGO, ONE COLOR','The world famous circle logo t-shirt for the folks that love maroon and white! This shirt features &#34;The Bird&#34; on the left chest and the circle logo on the back, all of it in maroon on a solid white shirt. - Gildan, 100% cotton, unisex',22.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_8798_grande.jpg?v=1483124151');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (1,'featured','THE BIRD HAT','The iconic logo of the Bird stands alone on the front of this black hat. If anyone is confused about what it is, DIXIE CHICKEN is written across the back. - Richardson 112, adjustable',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_8954_grande.jpg?v=1483475274');
INSERT INTO products(product_id,product_category,product_name,product_desc,product_price,product_image) VALUES (7,'men','''74 LONGSLEEVE','These super comfortable longsleeve shirts are just what you need to combat the cold! Take your pick of maroon or white to sport proudly at any A&M game. The white with maroon lettering looks particularly nice with the Reed Rowdies! - Comfort Colors, 100% cotton, unisex',25.00,'https://cdn.shopify.com/s/files/1/1660/2243/products/IMG_0245_grande.jpg?v=1484937533');
